guía de tipometría

* introducción
desarrollo a partir de guía básica usada en el idd en caracas como
material de apoyo en curso de tipografía, 1983

* agradecimientos

John Lange, director idd

* problemática

Enormes dificultades técnicas para producir tipografía
manualmente. Otro conjunto de dificultades para mantener alguna
normativa respecto a los cuerpos.

1. cada fundidor hacía exactamente lo que le daba la gana
2. cada cuerpo usaba nombre prosaico
3. los cuerpos no tenían proporcionalidad (ni siquiera siendo de un
   solo fabricante)
4. mercadeo de tipografía 

Fuentes:
Rowes Mores, Dissertation upon English Typographical Founders and Founderies
Moxon, Mechanick Exercises, v2?
Fournier, Manuel Typographique

* primeros pasos para obtener una solución

** Sebastién Truchet [André, tugboat]
** Pierre Simon Fournier [Manuel Typographique, google books]

* posteriores desarrollos

** cf Boag?

* actualidad

** el "big point" de adobe

* futuro?

** tipometría métrica?

Fuentes

* bibliografía
